spring:
  # 连接池配置
  datasource:
    url: jdbc:mysql://localhost:3306/network_community?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    #Redis服务器地址
    host: 123.57.239.63
    #Redis服务器连接端口
    port: 6379
    #Redis数据库索引（默认位0）
    database: 0
    #连接超时时间（毫秒）
    connect-timeout: 1800000
    password: 12438761015WPs
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        #最大阻塞等待时间（复数表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 5
        #连接池中的最小空闲连接
        min-idle: 0

oss:
  accessKey: Au1Tszq7zBY0rfxaKBKCXebdYDSSznay0zPsZjl9
  secretKey: RomxPgAXfCqcl9wnMC8yDL9TzGq4dDE8wuNAT4KD
  bucket: network-community
