spring:
  # 连接池配置
  datasource:
    url: jdbc:mysql://localhost:3306/network_community?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    #Redis服务器地址
    host: 192.168.75.201
    #Redis服务器连接端口
    port: 6379
    #Redis数据库索引（默认位0）
    database: 0
    #连接超时时间（毫秒）
    connect-timeout: 1800000
#    password: 12438761015WPs
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        #最大阻塞等待时间（复数表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 5
        #连接池中的最小空闲连接
        min-idle: 0



mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.haue.pojo #设置别名
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

ribbon:
  eager-load:
    enabled: true #开启饥饿加载提升第一次访问速度
    clients:
      - user-service #指定开启服务
feign:
  httpclient:
    enabled: true  # 开启httpClient开关,启动连接池,提升feign连接效率!
    max-connections: 200  #最大连接数量
    max-connections-per-route: 50  #单路径最大连接数
