# 配置网关
spring:
  cloud:
    gateway:
      routes:
        - id: article-service
          uri: lb://article-service
          predicates:
            - Path=/article/**  # 访问article路径转发用户服务;
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**  # 访问user路径转发用户服务
        - id: upload-service
          uri: lb://upload-service
          predicates:
            - Path=/upload/**  # 访问upload路径转发用户服务
        - id: article-service
          uri: lb://article-service
          predicates:
            - Path=/community/**  # 访问community路径转发用户服务
        - id: article-service
          uri: lb://article-service
          predicates:
            - Path=/activity/**  # 访问activity路径转发用户服务
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**  # 访问admin路径转发用户服务
#        - id: product-service # 此名称随意定义
#          uri: lb://product-service #使用负载均衡,调用服务名,这是服务名
#          predicates:
#            - Path=/product/** # 访问product相关,转发到product服务
